// Code generated by "stringer -type=State,Event"; DO NOT EDIT.

package simulation

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[StateWandering-0]
	_ = x[StateSick-1]
	_ = x[StateMovingToExit-2]
	_ = x[StateOutside-3]
	_ = x[StateBringingHoneyToStorage-4]
	_ = x[StateCollectingHoneyFromStorage-5]
	_ = x[StateCarryingHoney-6]
	_ = x[StateSupplyingHoneyToQueen-7]
}

const _State_name = "StateWanderingStateSickStateMovingToExitStateOutsideStateBringingHoneyToStorageStateCollectingHoneyFromStorageStateCarryingHoneyStateSupplyingHoneyToQueen"

var _State_index = [...]uint8{0, 14, 23, 40, 52, 79, 110, 128, 154}

func (i State) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_State_index)-1 {
		return "State(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _State_name[_State_index[idx]:_State_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EventWander-0]
	_ = x[EventSickness-1]
	_ = x[EventSicknessOver-2]
	_ = x[EventHoneySupplyLow-3]
	_ = x[EventWentOutside-4]
	_ = x[EventHarvestedHoney-5]
	_ = x[EventStoredHoney-6]
	_ = x[EventHoneySupplyOK-7]
	_ = x[EventReceivedHoney-8]
	_ = x[EventEggPlaced-9]
	_ = x[EventNoHoneyOnHand-10]
	_ = x[EventHoneyNeeded-11]
	_ = x[EventGettingHoney-12]
	_ = x[EventCollectedHoney-13]
	_ = x[EventBringingToQueen-14]
	_ = x[EventDeliveredHoney-15]
}

const _Event_name = "EventWanderEventSicknessEventSicknessOverEventHoneySupplyLowEventWentOutsideEventHarvestedHoneyEventStoredHoneyEventHoneySupplyOKEventReceivedHoneyEventEggPlacedEventNoHoneyOnHandEventHoneyNeededEventGettingHoneyEventCollectedHoneyEventBringingToQueenEventDeliveredHoney"

var _Event_index = [...]uint16{0, 11, 24, 41, 60, 76, 95, 111, 129, 147, 161, 179, 195, 212, 231, 251, 270}

func (i Event) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Event_index)-1 {
		return "Event(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Event_name[_Event_index[idx]:_Event_index[idx+1]]
}
